---
version: 2.1

executors:
  debian:
    docker:
      - image: debian:stretch

commands:
  save-workspace:
    steps:
      - persist_to_workspace:
          root: .
          paths:
            - ./

  restore-workspace:
    steps:
      - attach_workspace:
          at: .

jobs:
  test:
    executor: debian
    steps:
      - checkout
      - run:
          name: install luacheck
          command: |
            apt-get -qy update
            apt-get -qy --no-install-recommends install \
              build-essential \
              lua5.3 \
              lua5.3-dev \
              luarocks
            luarocks install luacheck
      - run: make lint
      - run: make test
      - save-workspace

  build:
    executor: debian
    steps:
      - restore-workspace
      - run: make build-deps-docs
      - run: make build-docs
      - run: make build-zip
      - save-workspace

  release:
    executor: debian
    steps:
      - restore-workspace
      - run:
          name: commit and push release artifacts back to github
          command: |
            echo TODO

workflows:
    main:
      jobs:
        - test
        - build:
            requires:
              - test
        - release:
            requires:
              - build
            filters:
              branches:
                only:
                  - master
                  - release-test